// <auto-generated />
namespace University.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update));
        
        string IMigrationMetadata.Id
        {
            get { return "201404061116284_Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
